### ISSUE TITLE
Support Treble and Non-Treble ROMs

### ISSUE THREAD

**Issue by bitrvmpd** [Loup-ROM/okami#17]
Just an idea, support both kind of ROMs using only a single zip. 

The only difference is on the DTB file.

**Comment by vvr3ddy** [comment]
You can probably take a look at Mostafa-Z's work He has managed to boot both builds on the same zip

**Comment by bitrvmpd** [comment]
Finally got the time to think about this :P https://github.com/bitrvmpd/AnyKernel3/commit/d48ba76037df400253971677adbaca0e8cbb56f3, https://github.com/bitrvmpd/AnyKernel3/commit/ae9c5e5c59ba47963af3f7ab48c87ab2605e7a06

Relevant files: 
https://github.com/bitrvmpd/AnyKernel3/blob/d48ba76037df400253971677adbaca0e8cbb56f3/anykernel-template.sh#L31-L32

https://github.com/bitrvmpd/AnyKernel3/blob/d48ba76037df400253971677adbaca0e8cbb56f3/anykernel-template.sh#L40-L41

https://github.com/bitrvmpd/AnyKernel3/blob/ae9c5e5c59ba47963af3f7ab48c87ab2605e7a06/tools/treble-tools.sh#L1-L22

Done!.
